AdobeDocs/adobe-io-runtime

- src/pages/guides/using/throughput_tuning.md
Add a section for using the Vary 
A question came to the product team about caching headers, this documentation section attempts to address this question going forward.
> Add section on Vary header

- src/pages/guides/getting-started/deploy.md
- src/pages/guides/overview/entities.md
- src/pages/guides/overview/howitworks.md
- src/pages/index.md
> fix: 404 links in Overview page for Guides (all links)

- src/pages/support/faq.md
Example:
1. Go to https://www.adobe.io/runtime/docs/support/faq/#getting-access
2. Click on the getting access link which goes here: https://www.adobe.io/runtime/docs/support/overview/getting_access.md
> fix: broken links in Support/FAQ

- src/pages/guides/getting-started/setup.md
Link was moved to App Builder docs.
> fix broken link

- src/pages/guides/reference/runtimes.md
`node-fetch@2.6.7` fixes a security issue. 
NOTE: this update will be in the next release, so please check with the Runtime team on Slack before this gets pulled in.
> fix: update node-fetch version in node 12 and 14 runtimes

- src/pages/guides/getting-started/setup.md
- [] I have added tests to cover my changes.
> fix: words and typos

- src/pages/guides/using/security_general.md
- src/pages/support/faq.md
Document the list of ports that can be used for external API calls.
> Allowed Egress Ports

- src/pages/guides/reference/runtimes.md
- `12.22.1` -> `12.22.12`
- `14.16.1` -> `14.20.0`
- `16.15.1` -> `16.17.0`
> update node minor versions

- src/pages/guides/using/creating_actions.md
Documentation on how to: 
- define activation error responses 
- handle async errors
> Documentation on how to properly deal with invocation errors

- src/pages/guides/using/logging_monitoring.md
Documentation on how to send action duration execution to New Relic
> Document how to integrate with New Relic

- src/pages/guides/using/securing_web_actions.md
- src/pages/guides/using/security_general.md
Documentation on how to:
- Use namespace credentials to http request non web actions
- Use App Builder tools to do IMS token validation
> Update documentation on how to secure actions

- src/pages/guides/using/security_general.md
Documentation on how to use a CDN with Runtime web actions
> CDN with Runtime web actions

- src/pages/guides/reference/configuringproxy.md
Reverts AdobeDocs/adobe-io-runtime#80
> Revert "Update configuringproxy.md"

- src/pages/guides/using/security_general.md
> Updating link

- src/pages/guides/reference/index.md
> Updating Index

- src/pages/guides/using/security_general.md
- src/pages/support/faq.md
* Add guidance on clients honoring DNS TTLs in the security guide
* Add networking FAQ about how Runtime ingress IPs are not static
* [RUNNER-6838](https://jira.corp.adobe.com/browse/RUNNER-6838)
> docs: add guidance on dns ttls

- src/pages/support/faq.md
updating faq to reflect node 18 as the default. Clarified the old version support to be execute only.
> update faq for node 18

- src/pages/guides/getting-started/setup.md
replace aio -h with aio help
https://github.com/AdobeDocs/adobe-io-runtime/issues/87
> Replace aio -h with aio help

- src/pages/guides/reference/runtimes.md
Adding info about node 20
Adding info about supporting node 20 as a runtime kind
ACNA-2517
manually validate in local dev environment
> Update runtimes page to support node 20

- src/pages/guides/reference/multiple_regions.md
after migrating from azure, we need to update which regions we operate in
Updating to show our 3 AWS regions
First discovered in IOEXT-628
Current docs are important!
Ran in local dev, checked for technical accuracy and grammar/spelling.
> Updating to AWS regions

- src/pages/guides/getting-started/activations.md
- src/pages/guides/getting-started/deploy.md
- src/pages/guides/overview/howitworks.md
- src/pages/guides/reference/feeds.md
- src/pages/guides/reference/packages.md
- src/pages/guides/reference/prepackages.md
- src/pages/guides/reference/runtimes.md
- src/pages/guides/reference/sequences_compositions.md
- src/pages/guides/reference/triggersrules.md
- src/pages/guides/tools/index.md
- src/pages/guides/using/asynchronous_calls.md
- src/pages/guides/using/creating_actions.md
- src/pages/guides/using/creating_rest_apis.md
- src/pages/guides/using/logging_monitoring.md
- src/pages/guides/using/securing_web_actions.md
- src/pages/guides/using/system_settings.md
- src/pages/guides/using/throughput_tuning.md
- src/pages/guides/using/using_packages.md
> RUNNER-7075: Replace WSK usage by AIO CLI

- src/pages/guides/overview/getting_access.md
> App Builder Trial link is 404

- package.json
- yarn.lock
See https://github.com/AdobeDocs/dev-site-documentation-template/commit/65a6c9966004dd34d1fa1c36419b75ce2d22cd10
> fix: added resolutions to latest for sharp and gatsby-sharp to fix deploy errors

- gatsby-config.js
- src/pages/guides/index.md
- src/pages/guides/using/index.md
- src/pages/guides/using/system_settings.md
- src/pages/guides/using/troubleshooting.md
- Added Troubleshooting section
- Described issues with exceeding pod local storage
Creating a new documentation section to provide details on common issues that customers can face
- tested on locally running instance of dev docs
> feat: troubleshooting-section

- src/pages/guides/using/throughput_tuning.md
Confirmed with team TTL is actually 5 minutes.
> Update warm container TTL

- src/pages/guides/using/creating_rest_apis.md
- Added a note regarding clean-up for unused custom APIs
> fix(RUNNER-7473): Archive remaining unused Custom API configs

- src/pages/guides/using/system_settings.md
- Updated the doc regarding max non-blocking timeout
> fix: Max non-blocking timeout
